# docker-compose.yml
version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "3011:3011"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iotdb
    ports:
      - "5432:5432"